- .travis.yml
Travis uses [several factors](https://docs.travis-ci.com/user/caching/#caches-and-build-matrices) to determine whether a given job shares a cache with a different job. In particular, it uses any environment variables specified in `.travis.yml`. Previously, integration tests set `INTEGRATION=true`, which meant that the integration tests did not share a cache with the non-integration tests, even though the compilation is exactly the same.
This patch fixes that by remvoing the `INTEGRATION` environment variable and instead using the globally available [`$TRAVIS_BUILD_STAGE_NAME`](https://docs.travis-ci.com/user/environment-variables/#default-environment-variables) to run the setup required for integration tests only in stages that run integration tests (namely integration and coverage). Now, …
> Avoid separate cache for integration tests

- src/client.rs
- src/parse.rs
NOOP should handle unsolicited responses.
> Handle unsolicited responses in noop.

- Cargo.toml
- src/lib.rs
- src/types/fetch.rs
- tests/imap_integration.rs
This method gives the internal date from the FETCH answer.
Fixes #112
> Add Fetch.internal_date method

- Cargo.toml
- src/client.rs
- src/error.rs
- src/parse.rs
- Regex is lazy init.
- Removes two allocations and a panic.
- Breaking change on DataNotUtf8 (wasn't used).
> Improve auth resp parsing

- Cargo.toml
- azure-pipelines.yml
- examples/README.md
- examples/rustls.rs
- src/client.rs
By checking this code in as an example, we can prevent bitrot as we continuously test this
in CI. It also demonstrates how to setup TLS without relying on platform specific dependencies
via native_tls crate.
First step of https://github.com/jonhoo/rust-imap/issues/123
> (feat) Provide example integration with Rustls crate

- src/client.rs
- src/error.rs
This is needed when manually using `Client::new()`.
> feat: expose read_greeting

- src/client.rs
When authenticating using SASL XAUTH2 with Gmail the imap library waits forever to read data from the Google servers. I think this is because they send a message explaining that the server is ready even though the imap library expects a response regarding authentication.
Running debug mode looks like this:
```
C: a1 AUTHENTICATE XOAUTH2
S: * OK Gimap ready for requests from IP u21mb6660826edd
S: + 
```
I'm obviously missing tests and such and I don't even know if this is actually a proper fix bug wanted to report the bug and at least share my solution.
> When authenticating using SASL XAUTH2 with Gmail fails

- src/lib.rs
Quite a few crate (serde_json, postgres, reqwest, std::io) re-export the error type from their error module, so I thought it would be good if this crate did as well.
I found myself trying to use imap::Error rather than imap::error::Error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/170)
> Re-export Result and Error types

- azure-pipelines.yml
Nightly pipeline is failing on missing rustfmt, but we don't actually need it except for the beta version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/173)
> CI: Only install components when needed.

- src/client.rs
- tests/imap_integration.rs
References issue #60
Followed syntax of (date-time token) http://www.faqs.org/rfcs/rfc3501.html
I followed the pattern of `append` calling `append_with_flags` calling `append_with_flags_and_date`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/174)
> feat: allow setting sent date on APPEND

- src/client.rs
- tests/imap_integration.rs
This is an attempt to simplify append by squashing the three variants into to one command + an options struct `AppendOptions`.
This PR also provides a command builder `AppendCmd` to simplify construction of the options struct as [suggested here](https://github.com/jonhoo/rust-imap/pull/174#issuecomment-745000597) and onwards:
```rust
session.append(
mbox,
e.message_to_string().unwrap(),
AppendCmd::new()
.flag(Flag::Seen)
.internal_date(&date)
);
```
---
Thoughts not related to what is implemented:
- If `AppendCmd` builds options maybe it should be called `AppendOptionsBuilder` (very long)
- and if so what `AppendCmd` look like:
```rust
struct AppendCmd {
mbox: ..,
content: ..,
// impl
pub fn run(&self) -> ...;
pub fn with_options(&self) -> AppendOptionsBuilder {
AppendOptionsBuilder { …
```
> refactor: squash append command

- CHANGELOG.md
- Cargo.toml
- azure-pipelines.yml
- src/client.rs
- src/error.rs
- src/parse.rs
- src/types/deleted.rs
- src/types/mailbox.rs
- src/types/mod.rs
This adds support for imap-proto `ResponseCode::HighestModSeq(u64)` and the `VANISHED` response described in RFC 7162 (QRESYNC). With these extensions, it is possible to synchronize a mailbox in a single round trip using `UID FETCH` and passing a modifier `(CHANGEDSINCE <MODSEQ> VANISHED)`. Only modifications and new messages since `<MODSEQ>` will be returned, and deleted messages will be returned in a `VANISHED` response on the `unsolicited_responses` channel.
Technically, if `QRESYNC` is enabled then `VANISHED` responses will be sent to `EXPUNGE` commands. Presently these will show up on the `unsolicited_responses` channel even though they are directly a response to a command. I wasn't sure what the best way to handle this would be in `parse_expunge()`, and commented to this effect in …
> Support HIGHESTMODSEQ and VANISHED

- src/client.rs
- src/extensions/metadata.rs
- src/extensions/mod.rs
- src/parse.rs
- src/types/mod.rs
Add support for METADATA IMAP extension, RFC-5464
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/149)
> Adding METADATA support

- README.md
Small changes to doc to match docker version in `docker pull` and `docker run`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/181)
> Doc: match image version from docker pull

- src/client.rs
- src/extensions/metadata.rs
- src/parse.rs
While working on handling unsolicited responses in the other branch, bumped into these:
- Rename `handle_unilateral` to `try_handle_unilateral` because [suggested here](https://github.com/jonhoo/rust-imap/pull/130#discussion_r316369815).
- Make clippy happy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/184)
> Try handle unsolicited & clippy

- src/parse.rs
Thanks clippy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/188)
> Remove redundant slice.

- Cargo.toml
Simplifying the dependency tree slightly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/189)
> Remove unused features from chrono, nom

- Cargo.toml
- src/client.rs
- src/extensions/mod.rs
- src/extensions/sort.rs
- src/parse.rs
- tests/imap_integration.rs
#178
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/180)
> RFC 5256 - SORT command

- Cargo.toml
Hi,
Since the commit 514735e9204ca7cc6e307d43c08d7827bea4bd6d which remove the "default features" for the dependency 'chrono', I now have this error : 
```
imap-3.0.0-alpha.3/src/client.rs:202:37
format!(" \"{}\"", date.format("%d-%h-%Y %T %z"))
^^^^ method not found in `DateTime<FixedOffset>>` 
```
So I think we have to add back the 'std' feature to 'chrono'
```
chrono = {version = "0.4", default-features = false, features = ["std"]}
```
(I know that I could add this dependency to my project Cargo.toml (and I did), but I think this should be in rust-imap)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/195)
> 3.0.0-alpha.3: missing 'std' feature for 'chrono'

- src/parse.rs
Follow up on #179.
We seem to have handled this with the recent work on `UnsolicitedResponse`, so I just added a test to make sure we continue to handle this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/196)
> Add test for dovecot unsolicited OK progress message.

- .cirrus.yml
- Cargo.toml
- README.md
- azure-pipelines.yml
- codecov.yml
- examples/README.md
- examples/basic.rs
- examples/gmail_oauth2.rs
- examples/idle.rs
- examples/rustls.rs
- examples/starttls.rs
- examples/timeout.rs
- src/client.rs
- src/client_builder.rs
- src/error.rs
- src/extensions/idle.rs
- src/lib.rs
- src/types/deleted.rs
- tests/imap_integration.rs
Addresses #190 
Also add support for rustls in addition to native-tls. I think using `rustls` should be easier (and could even be the default?), so I just made it first class like `native-tls`. I have tested both the `native_tls()` and `rustls()` paths.
This just adds the `ClientBuilder`. If we're happy with the API here and the way it works, then I can take care of:
- Fixing up the examples (doc and `/examples`) to use it where appropriate.
- If we want to get rid of any code that is superseded by this?
I have not tested the STARTTLS code, since I do not have a STARTTLS enabled server to work with. How do we want to handle automating the tests to make sure it all works?
I have not added it, but I can see an argument for adding some knobs to control which CA bundle is added, or adding …
> Add ClientBuilder helper to make setting up TLS connections easy.

- CHANGELOG.md
I added breaking changes I noticed while integrating the `v3.0.0-alpha.3` in my tool: https://github.com/soywod/himalaya/commit/36d3cd63475ed63cd78c9328cc0fbed310b481f6. I also replaced the `v3.0.0 - ???` with `Unreleased`, let me know if it's okey.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/199)
> Update changelog for v3

- src/client.rs
- src/error.rs
- src/parse.rs
- tests/imap_integration.rs
Fixes #185.
My use of ParseError::Unexpected for error messages feels a bit sketchy,
but I wasn't sure how you'd prefer to handle them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/192)
> Support parsing STATUS responses.

- Cargo.toml
- src/client.rs
- src/client_builder.rs
- src/error.rs
- src/extensions/idle.rs
- src/lib.rs
- src/types/deleted.rs
- tests/imap_integration.rs
Suggested [here](https://github.com/jonhoo/rust-imap/pull/197#discussion_r629806956) and it's a good idea. :-)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/201)
> Change "tls" feature to "native-tls"

- CHANGELOG.md
- Cargo.toml
- examples/idle.rs
- src/client.rs
- src/client_builder.rs
- src/error.rs
- src/extensions/idle.rs
- src/lib.rs
- src/types/deleted.rs
- tests/imap_integration.rs
Addresses #191 .
Also includes the changes in #201 for convenience.
Note that this change effectively requires that the underlying transport implements the `SetReadTimeout` trait from `extensions::idle`. I am not sure if this is a problem or not. If so, I can add the old `wait_while()` back with a different name (`wait_notimeout_while()`?) to restore the functionality. I opted to remove it because the old `wait_keepalive_while` function was already broken for non-`SetReadTimeout` transports, and it was the recommended way to do it. I am unsure if the extra API is worth it since implementing `SetReadTimeout` is so trivial. Happy to get feedback on this.
Note that this also makes `keepalive` the default, since it is the recommended way to do it. An opt-out function is provided …
> Idle builder

- Cargo.toml
- examples/gmail_oauth2.rs
- src/client.rs
- src/parse.rs
- src/types/capabilities.rs
- src/types/fetch.rs
- src/types/flag.rs
- src/types/mod.rs
- src/types/name.rs
- tests/imap_integration.rs
This converts `Capabilities` to use ouroboros instead of the local `ZeroCopy`.
Because of all the magic that ouroboros `self_referencing` macro adds (`CapabiltiesTryBuilder` and friends) I found it was simpler to move the parsing bit into the `Capabilities` struct itself. I actually prefer this, since it keeps everything related to `Capabilities` in one place, but I understand if you prefer to keep everything related to parsing in `parse.rs`.
Anyway, if this approach for moving from `ZeroCopy` to ouroboros looks like a good approach, then I can do the rest of it similarly here, and `ZeroCopy` can go away, and we can close #125 .
Thoughts?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Convert ZeroCopy to ouroboros.

- src/client.rs
- src/error.rs
- src/extensions/metadata.rs
In addition to the invalid character, the error now also contains a
`command_synopsis` and `argument` which identifies the command and
argument that failed to validate.
Fixes #215 
Currently the error message just shows a "synopsis" of the command, e.g., `FETCH seq query`, not the actual arguments. Maybe it makes sense to also show the invalid argument value.. except if it is a secret of course. If you think this is a good idea, and provided this PR goes into the right direction, I can add this functionality also.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/218)
> Improve error message for `ValidationError`

- src/types/fetch.rs
If the QRESYNC (RFC 7162) extension is being used, a FETCH response to a
STORE or UID STORE command with the UNCHANGEDSINCE query attribute will
return the mod sequence ID of the performed operation. This information
is crucial for building efficient caching clients.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/233)
> Expose MODSEQ attribute in FETCH responses

- src/client.rs
- src/parse.rs
- src/types/deleted.rs
If the `QRESYNC` extension (RFC 7162) is being used, `EXPUNGE` responses
will return the new highest mod sequence for the mailbox after the
expunge operation. Access to this value is quite valuable for caching
clients.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/234)
> Expose HIGHESTMODSEQ value in EXPUNGE response

- README.md
The instructions on running the integration tests use an outdated
version of Greenmail with which the tests will not pass. Update it to
the latest version, like in the pull command above it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/237)
> README: fix Greenmail version in example command

- src/client.rs
- src/parse.rs
- src/types/appended.rs
- src/types/mod.rs
If the `UIDPLUS` extension is supported, the server will reply to
`APPEND` commands with the UID of the new message. This can even be a
list of UIDs if the `MULTIAPPEND` extension is also supported.
Make this information available to the user as the result of an
`AppendCmd`. The added doc strings have links to the relevant RFCs.
Related to #131.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/232)
> Add support for APPENDUID response data

- src/client.rs
Just a minor doc fix, thanks for this crate :blue_heart:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/226)
> doc: reference ::mv, not ::copy, from ::uid_mv

- .github/workflows/test.yml
- Cargo.toml
- src/client.rs
- src/parse.rs
- src/types/acls.rs
- src/types/mod.rs
- tests/imap_integration.rs
Requires djc/tokio-imap#142 (now merged, awaiting crate release) to handle the parsing-side of the responses.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/227)
> add in ACL extension support

- src/client.rs
- src/lib.rs
- src/parse.rs
- src/types/acls.rs
- src/types/mod.rs
- src/types/quota.rs
- src/utils.rs
- tests/imap_integration.rs
Here is my first-stab at adding in support for the quota extension (already in imap-proto).
A few things I don't like with it right now.
1. it exposes some of the imap-proto structs (QuotaResource)
- I can create local QuotaResource and map them.
2. the "getquotaroot" is "fun" as it returns 2 resources, (1) QUOTAROOT and (n) QUOTAs.
- The issue here is that I have to run parse_many_into twice to get both resource sets. (unless I just don't use parse_many_into and just duplicate most of that in the method which I may do)
- this also causes a difference in response types..  e.g. set_quota and get_quota return a local Quota struct, but I the get_quota_root returns the imap-proto Quota struct (I did not see any easy way to convert ouroboros structs).
Anyways, it's starting point.. Please …
> add support for the imap quota extension (RFC 2087)

- src/types/acls.rs
- src/types/capabilities.rs
- src/types/fetch.rs
- src/types/name.rs
As @jonhoo pointed out [here](https://github.com/jonhoo/rust-imap/pull/249#pullrequestreview-1249037461), the various types' `parse()` functions should not be exported. Some are, though. The 3.0 release is probably a good time to fix that.
Note: some types (e.g. `Mailbox`, `Deleted`) didn't have their `parse()` function exposed, so I think it's pretty safe to assume that nobody built anything seriously using these.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/251)
> Un-export some exposed `parse()` functions

- src/client.rs
- src/extensions/list_status.rs
- src/extensions/mod.rs
- tests/imap_integration.rs
See https://tools.ietf.org/html/rfc5819
Hi there. I would love to add support for RFC 5819. It is extremely valuable for clients to perform a full mailbox sync with as little requests as possible. This patch is not yet well-documented, but I wanted to get some feedback early on, specifically on the following:
- I implemented it as an extension, in the `extensions` folder. I think it makes sense there, but it could of course be done differently, potentially even merged with the regular `LIST` command, though I think that would make the API a little awkward.
- I took some cues from the `Names` data structure. I hope the name `ExtendedNames` makes sense, as this version of `LIST` is usually referred to as "extended LIST".
- Instead of creating a struct for each single response I opted for …
> Add support for RFC 5819: LIST-STATUS extension

- src/types/quota.rs
In using the quota feature in my application (finally) I noticed that I was running into life-time specifier issues trying to convert my input String into a QuotaResourceLimit through the Into<QuotaResourceName> argument.
I had to resort to re-implementing my own match line to convert into an Owned QuotaResourceName.
This PR adds an implementation of From<String> for QuotaResourceName<'_> so strings can be utilized as well as &str.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/272)
> Implement From<String> for QuotaResourceName

- .github/workflows/scheduled.yml
- .github/workflows/test.yml
- Cargo.toml
- README.md
- examples/basic.rs
- examples/gmail_oauth2.rs
- examples/idle.rs
- examples/rustls.rs
- examples/starttls.rs
- src/client.rs
- src/client_builder.rs
- src/conn.rs
- src/error.rs
- src/extensions/idle.rs
- src/lib.rs
- src/types/deleted.rs
- tests/builder_integration.rs
- tests/imap_integration.rs
- this allows a more transparent and versatile usage of the library as one can simply compile it as-is and then use the builder to configure where we connect and how we connect without having to be concerned about what type is used for the imap::Client / imap::Session
This is inspired by how the ldap3 library hides-away the connection of ldap, ldaps, or ldapi (unix socket)
IMHO this should just be the main ClientBuilder, however, the methodology used in this PR requires that only either rustls OR nativetls be active, not both. So this PR adds it as a parallel client builder.
Implements issue described in #244 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/245)
> add in a client builder that abstracts away connecting to TLS or non-TLS connections and what TLS provider is used.

- .github/workflows/test.yml
- README.md
Hint to use the newer (stable) `1.6.15` version.
All tests still pass.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/281)
> Update greenmail docker image version in README.

- src/client.rs
- src/error.rs
This is just a fork of https://github.com/jonhoo/rust-imap/pull/231 so it can be finished and merged.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/284)
> Refactor tag assertion to FatalError check & Fix unexpected increase of tag (fork)

- .github/workflows/check.yml
- examples/README.md
- src/client.rs
- src/error.rs
- src/extensions/idle.rs
- src/extensions/list_status.rs
- src/extensions/metadata.rs
- src/extensions/sort.rs
- src/types/deleted.rs
- src/types/unsolicited_response.rs
Fix various [typos](https://github.com/crate-ci/typos) and run typos in CI-.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/289)
> typos: init and run in ci 

- Cargo.lock
No need to bump Cargo.toml in Rust.
Closes #291
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/292)
> Bump openssl for dependabot

- Cargo.toml
- src/client.rs
- src/extensions/list_status.rs
- src/extensions/metadata.rs
- src/parse.rs
- src/testing.rs
- src/types/acls.rs
- src/types/capabilities.rs
- src/types/fetch.rs
- src/types/name.rs
- src/types/quota.rs
- tests/imap_integration.rs
Fixes #254.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/260)
> Replace mpsc::{Sender,Receiver} by VecDeque

- Cargo.lock
- Cargo.toml
- src/client.rs
I honestly couldn't tell you why `NO_PAD` was chosen. It seems to have happened somewhat arbitrarily when the `base64` major upgrade that introduced the distinction landed in #253.
Time to fix that.
Fixes #299.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/305)
> Allow padded authentication tokens
