src/client.rs
=> Fix quoting issue in LIST command

src/types/capabilities.rs
Related djc/tokio-imap/issues/54
=> Make capabilities has_str case insensitive

src/client.rs
data_times should be data_items for
function "status"
Fixes #146
=> Fix typo in documentation

src/client.rs
Some servers (yandex) will send a single `"+"` as response when using XOAUTH2. 
(the first commit is from #144, can be ignored here)
=> fix(client): handle single "+" in auth server response 

src/client.rs
Add a `imap::connect_starttls` convenience function, with the same
syntax as `imap::connect`, to make STARTTLS connections as easily as
IMAPS.
PR#140 removed `imap::connect_insecure` with the stated goal of
encouraging users to connect securely. With that change, users are
forced to construct their own `TcpStream`s when interacting with
non-IMAPS servers.
This change may perversely incentivise the use of insecure connections,
instead of discouraging them, as users may blindly copy-paste code
involving `Client::new` and `TcpStream`s so things "just work", without
the visual indicator of `_insecure` suggesting something is wrong.
Tangentially, [RFC 2595] encourages using STARTTLS instead of raw SSL
sockets. Ideally, we should support both options equally well.
[RFC 2595]: …
=> Add `imap::connect_starttls` convenience function

src/error.rs
Since Error::description was deprecated in rust 1.42, the use of description() causes warnings. I suspect that you don't want to delete the existing implementation of these deprecated functions just yet.
This PR updates the implementation of Display to not rely on description(), and marks the uses found in the existing description() implementation as allowed in order to suppress the warnings there.
You should be able to just delete the implementations of Error::description and Error::cause whenever you're comfortable doing that.
If you don't want to merge this that's okay with me. I just saw the warnings and thought I could help make them go away in a forward-looking but backwards-compatible way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> Make Display implementation independent of Error::description

src/extensions/idle.rs
These messages show up at an interval controlled by Dovecot's imap_idle_notify_interval setting, which defaults to 2 minutes. These messages were causing the IDLE loop to exit prematurely because it looks like a notification response from the server. This means that IDLE connections to servers that do this are short lived.
With this change, these "OK Still here" messages instead keep the IDLE session alive indefinitely unless the socket timeout is less than the server notify interval. When something changes on the mailbox, the normal notification (FETCH, EXISTS, etc.) causes the IDLE loop to exit as before and return to the client.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Handle Dovecot's periodic IDLE notification messages ("OK Still here").

src/extensions/idle.rs
I also had the issue described [here](https://github.com/jonhoo/rust-imap/issues/139), so I did a quick patch that is certainly not elegant (and keep in mind this is my first rust ever), but seems to work for me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/159)
=> Support timing out wait on IDLE

src/parse.rs
Fixes #161 (well, the side-issue in #161).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/162)
=> FLAGS can be sent as unilateral response

src/client.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/164)
=> Changed: a typo was fixed

examples/starttls.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/165)
=> Added: STARTTLS example

azure-pipelines.yml
- bump MSRV because of dependencies
- update azure pipelines version
- update greenmail image
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/169)
=> Make CI pass on `master` again

examples/README.md, examples/timeout.rs, src/client.rs
fixes #167
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/168)
=> server greeting doc and timeout example

CHANGELOG.md, src/client.rs
Also, apply correct validation to FETCH arguments.
This should fix #176.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/177)
=> Avoid trying to FETCH an empty set of messages

azure-pipelines.yml, src/parse.rs, src/types/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/163)
=> More unilaterals

CHANGELOG.md
Correct oversight.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/203)
=> Update CHANGELOG for feature name change.

src/client.rs, src/types/fetch.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/204)
=> fixes doc typos

Cargo.toml, src/parse.rs, src/types/fetch.rs, src/types/mod.rs, src/types/name.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/225)
=> Add support for Gmail Labels

.github/workflows/test.yml, README.md, tests/imap_integration.rs
Adds cyrus-imapd support for testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/228)
=> update integration tests to work against cyrus imapd

tests/imap_integration.rs
Ignored by default as it only works with Cyrus, not with Greenmail.
Test functionality added in #233 and #234.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/238)
=> Add integration test for QRESYNC extension

.github/codecov.yml, .github/workflows/coverage.yml, .github/workflows/features.yml, .github/workflows/minimal.yml, .github/workflows/msrv.yml, .github/workflows/os-check.yml, .github/workflows/style.yml, .github/workflows/test.yml, src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/241)
=> Refresh CI scripts

examples/README.md, examples/plaintext.rs
I found the documentation lacking in a simple plain text connection. It took me a bit to figure it out but I did (I'm a Rust beginner after all). I'm hoping others will find this useful.
(Addressing #247)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/248)
=> Addresses #247 - Plaintext IMAP Connection Example

.github/workflows/check.yml, .github/workflows/test.yml, Cargo.lock, Cargo.toml, src/client.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/253)
=> Bump base64 dependency

.github/workflows/check.yml, .github/workflows/scheduled.yml, .github/workflows/test.yml
https://github.com/jonhoo/rust-ci-conf
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/256)
=> Merge from CI repo

Cargo.lock, Cargo.toml
and thus bump rustls to v0.21
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/267)
=> bump rustls-connector to v0.18.1

Cargo.toml, src/lib.rs, src/testing.rs, src/types/quota.rs
Allows building response objects for testing applications that use this crate.
Implements a possibility to resolve #261 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/262)
=> Create a testing module that includes helper methods to build mock responses for testing

.github/workflows/check.yml, Cargo.lock, Cargo.toml, src/client.rs, src/client_builder.rs, src/error.rs, src/extensions/idle.rs, src/extensions/list_status.rs, src/extensions/metadata.rs, src/parse.rs, src/testing.rs, src/types/acls.rs, src/types/appended.rs, src/types/capabilities.rs, src/types/deleted.rs, src/types/flag.rs, src/types/name.rs, src/types/quota.rs, src/types/unsolicited_response.rs, tests/builder_integration.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/rust-imap/285)
=> Various fixups
